# Generated by Django 4.2.3 on 2023-08-11 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soulsbornestore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.TextField(max_length=10)),
                ('desc', models.TextField(max_length=100)),
                ('name', models.TextField(max_length=50)),
                ('pid', models.TextField(max_length=50)),
                ('score', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.TextField(max_length=10)),
                ('total', models.IntegerField(default=1)),
                ('username', models.TextField(max_length=50)),
                ('date', models.DateField()),
            ],
        ),
    ]
