# Generated by Django 4.2.3 on 2023-08-11 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soulsbornestore', '0002_review_sales'),
    ]

    operations = [
        migrations.CreateModel(
            name='sales1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.TextField(max_length=100)),
                ('total', models.IntegerField(default=1)),
                ('username', models.TextField(max_length=50)),
                ('date', models.DateField()),
            ],
        ),
    ]
