# Generated by Django 4.2.3 on 2023-08-11 11:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soulsbornestore', '0004_alter_sales1_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales1',
            name='date',
            field=models.DateField(null=True, verbose_name=datetime.datetime(2023, 8, 11, 16, 57, 16, 697736)),
        ),
    ]
