# Generated by Django 4.2.3 on 2023-08-12 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soulsbornestore', '0005_alter_sales1_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='sales1',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
