# Generated by Django 4.2.3 on 2023-08-12 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soulsbornestore', '0007_reviewmk1'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminusers',
            name='Emailid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customusers',
            name='Emailid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
